spring.application.name=courserecommend
spring.datasource.url=jdbc:postgresql://localhost:5432/courserecommend
spring.datasource.username=postgres
spring.datasource.password=123456789za
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
