spring.application.name=courserecommend

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/courserecommend}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

springdoc.swagger-ui.path=/swagger-ui.html
